Guia: GitHub Actions
1. Asegurate que el repositorio tenga los archivos Dockerfile y session.yaml
proyecto-vise/
├─ Dockerfile
├─ session.hurl
├─ el resto del código
2. Nos ubicamos en el repositorio de nuesta API VISE y nos dirigimos a la sección Actions
3. Creamos un workflow en blanco
4. Ingresamos las instrucciones de la acción:
# Nombre de la action
name: Build container and run VISE API testing

on:
  workflow_dispatch:
    inputs:
      PORT:
        description: 'The port of your application'
        required: true
        default: "3000"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: |
          docker build -t vise-api:latest .

      - name: Run container
        run: |
          docker run -d -p ${{ github.event.inputs.PORT }}:${{ github.event.inputs.PORT }} --name vise-api vise-api:latest
          sleep 5

      - name: Setup hurl (API testing tool)
        uses: gacts/install-hurl@v1

      - name: Test API
        run: hurl --variable host=http://localhost:${{ github.event.inputs.PORT }} --error-format long --test session.hurl